general {
    lock_cmd = hyprctl eval 'hl.dsp.global("caelestia:lock")'
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = hyprctl eval 'hl.dsp.global("caelestia:lock")'
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
